# Generated by Django 2.1.8 on 2019-05-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='site_code',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
