# Generated by Django 2.2.1 on 2019-05-16 13:22

from django.db import migrations, models
import django.db.models.deletion
import test_page.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsnapshotpublisher', '0004_auto_20190423_1417'),
        ('test_page', '0002_auto_20190502_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='content_release',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=models.Q(('status', 0), ('status', 1), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitesettings_content_release', to='wagtailsnapshotpublisher.WSSPContentRelease'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='publish_to_live_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_code',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='body',
            field=wagtail.core.fields.StreamField([('simple_richtext', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('body', wagtail.core.blocks.RichTextBlock(required=False))], icon='title')), ('dynamictestpage_block', test_page.models.DynamicTestPageBlock('test_page.TestPage'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site'),
        ),
        migrations.AlterField(
            model_name='testpage',
            name='body',
            field=wagtail.core.fields.StreamField([('simple_richtext', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('body', wagtail.core.blocks.RichTextBlock(required=False))], icon='title')), ('block_list', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('body', wagtail.core.blocks.StreamBlock([('simple_richtext', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('body', wagtail.core.blocks.RichTextBlock(required=False))], icon='title'))], null=True))])), ('dynamictestpage_block', test_page.models.DynamicTestPageBlock('test_page.TestPage'))], null=True),
        ),
    ]
