# Generated by Django 2.1.7 on 2019-03-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangosnapshotpublisher', '0004_auto_20190328_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSSPContentRelease',
            fields=[
                ('contentrelease_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangosnapshotpublisher.ContentRelease')),
            ],
            options={
                'verbose_name': 'Releases',
            },
            bases=('djangosnapshotpublisher.contentrelease',),
        ),
    ]
