# Generated by Django 2.1.8 on 2019-04-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsnapshotpublisher', '0002_create_developer_access_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsspcontentrelease',
            name='version_type',
            field=models.IntegerField(choices=[(0, 'MAJOR'), (1, 'MINOR'), (2, 'PATCH')], default=1),
        ),
    ]
