# Generated by Django 2.1.8 on 2019-04-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsnapshotpublisher', '0003_wsspcontentrelease_version_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsspcontentrelease',
            name='restored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wsspcontentrelease',
            name='version_type',
            field=models.IntegerField(choices=[(0, 'MAJOR'), (1, 'MINOR')], default=1),
        ),
    ]
